language: python

sudo: false
dist : xenial
python:
  - "3.7"

os:
  - linux

before_install:
  - chmod +x entry.sh

script:
  ./entry.sh

after_success:
  - codecov
  
after_script:
  python setup.py install
  python tests/after_install/post_install_script.py
