language: python

sudo: false
dist : xenial
python:
  - "3.7"

os:
  - linux

script:
  coverage run -m unittest discover;

after_success:
  python setup.py install

after_script:
  python tests/after_install/post_install_script.py
